global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'umbilical-choir'
    honor_labels: true
    static_configs:
      - targets: ['host.docker.internal:9091']